src/MvcMovie/Models/ErrorViewModel.cs
using System;

namespace MvcMovie.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MvcMovie/Models/SampleHelper.cs
using System.Linq;

namespace MvcMovie.Models
{
    public static class SampleHelper
    {
        public static SamplePostParameterViewModel Sort(SamplePostParameterViewModel parameter)
        {
            // バブルソート
            // バブルソートの計算量はO(n^2)なので超非効率！
            for (var i = 0; i < parameter.Numbers.Count; i++)
            {
                for ( var j = i + 1; j < parameter.Numbers.Count; j++) {
                    if (parameter.Numbers[i] > parameter.Numbers[j]) {
                        var tmp = parameter.Numbers[i];
                        parameter.Numbers[i] = parameter.Numbers[j];
                        parameter.Numbers[j] = tmp;
                    }
                }
            }

            return parameter;
        }

        public static SamplePostParameterViewModel SortDescending(SamplePostParameterViewModel parameter)
        {
            // バブルソート
            // バブルソートの計算量はO(n^2)なので超非効率！
            for (var i = 0; i < parameter.Numbers.Count; i++)
            {
                for ( var j = i + 1; j < parameter.Numbers.Count; j++) {
                    if (parameter.Numbers[i] > parameter.Numbers[j]) {
                        var tmp = parameter.Numbers[i];
                        parameter.Numbers[i] = parameter.Numbers[j];
                        parameter.Numbers[j] = tmp;
                    }
                }
            }

            return parameter;
        }

        public static bool Exist(SamplePostParameterViewModel parameter)
        {
            // TODO: 処理がないのでテストコードが通るように処理を書きましょう
            return true;
        }

        // TODO: 値のリストを受け取って最大値を返却するメソッドを定義してみましょう

        // TODO: 受け取った数値分のフィボナッチ数をすべて返すメソッドを定義してみましょう
        // 例えば「5」を受け取った場合に返却される値は「0, 1, 1, 2, 3」です。
        // 「10」を受け取った場合は「0, 1, 1, 2, 3, 5, 8, 13, 21, 34」です。

    }
}

src/MvcMovie/Models/SamplePostParameterViewModel.cs
using System.Collections.Generic;

namespace MvcMovie.Models
{
    public class SamplePostParameterViewModel
    {
        public IList<int> Numbers { get; set; }
        public int? Number{ get; set; }
    }
}

src/MvcMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MvcMovie/Controllers/SampleController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class SampleController : Controller
    {
        [HttpPost]
        public IActionResult Sort(SamplePostParameterViewModel parameter)
        {
            parameter = SampleHelper.Sort(parameter);

            return View(parameter);
        }

        [HttpPost]
        public IActionResult SortDescending(SamplePostParameterViewModel parameter)
        {
            parameter = SampleHelper.SortDescending(parameter);

            return View("Sort", parameter);
        }

        [HttpPost]
        public IActionResult Exist(SamplePostParameterViewModel parameter)
        {
            var existValue = SampleHelper.Exist(parameter);

            return View(existValue);
        }
    }
}

src/MvcMovie/Views/Home/Index.cshtml
@model MvcMovie.Models.SamplePostParameterViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<form method="POST">
    <div>
        <input asp-for="Numbers" value="1"/><br/>
        <input asp-for="Numbers" value="3"/><br/>
        <input asp-for="Numbers" value="4"/><br/>
        <input asp-for="Numbers" value="2"/><br/>
        <input asp-for="Numbers" value="1"/><br/>
        <input asp-for="Numbers" value="3"/><br/>
        <input asp-for="Numbers" value="10"/><br/>
        <input asp-for="Numbers" value="9"/><br/>
    </div>
    <input type="submit" value="ソート(昇順)" asp-controller="Sample" asp-action="Sort"/>
    <input type="submit" value="ソート(降順)" asp-controller="Sample" asp-action="SortDescending" />
</form>

<br/>
<form method="POST">
    <div>
        リスト<br/>
        <input asp-for="Numbers" value="1"/><br/>
        <input asp-for="Numbers" value="3"/><br/>
        <input asp-for="Numbers" value="4"/><br/>
        <input asp-for="Numbers" value="2"/><br/>
        <input asp-for="Numbers" value="1"/><br/>
        <input asp-for="Numbers" value="3"/><br/>
        <input asp-for="Numbers" value="10"/><br/>
        <input asp-for="Numbers" value="9"/><br/>
    </div>
    <div>
        検索値<br/>
        <input asp-for="Number" value="5"/>
    </div>
    <input type="submit" value="検索" asp-controller="Sample" asp-action="Exist" />
</form>

src/MvcMovie/Views/Sample/Exist.cshtml
@model bool

リストの中に値は
@if(Model)
    {
        @:ありました。
    }
    else
    {
        @:ありませんでした。
    }


src/MvcMovie/Views/Sample/Sort.cshtml
@model MvcMovie.Models.SamplePostParameterViewModel

@{
    ViewData["Title"] = "Sample";
}

@foreach (var items in Model.Numbers) {
    <div>
        @Html.DisplayFor(x => items)
    </div>
}

src/MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMovie</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>